<?php

namespace App\Enum;

/**
 * TerrainType enum defining all available terrain types for the hexagonal map
 * 
 * Each terrain type has associated properties including visual color,
 * movement cost, defense bonus, and resource value. These properties
 * affect gameplay mechanics and visual representation in the game.
 */
enum TerrainType: string
{
    /** @var string Plains terrain - basic grassland with moderate properties */
    case PLAINS = 'plains';
    
    /** @var string Forest terrain - wooded areas with high defense and resources */
    case FOREST = 'forest';
    
    /** @var string Mountain terrain - elevated areas with highest defense and resources */
    case MOUNTAIN = 'mountain';
    
    /** @var string Water terrain - impassable water bodies */
    case WATER = 'water';
    
    /** @var string Desert terrain - arid areas with low resources */
    case DESERT = 'desert';
    
    /** @var string Swamp terrain - marshy areas with high movement cost */
    case SWAMP = 'swamp';

    /**
     * Gets the properties associated with this terrain type
     * 
     * Returns an array containing all gameplay and visual properties
     * for the terrain type. Properties include name for display,
     * color for rendering, movement cost for pathfinding, defense 
     * bonus for combat, and resource value for economy.
     * 
     * @return array Associative array containing:
     *               - 'name': string display name for the terrain
     *               - 'color': int hexadecimal color value for rendering
     *               - 'movementCost': int cost to move through this terrain (0 = impassable)
     *               - 'defense': int defensive bonus when positioned on this terrain
     *               - 'resources': int resource value generated by this terrain
     */
    public function getProperties(): array
    {
        return match($this) {
            self::PLAINS => [
                'name' => 'Plains',
                'color' => 0x90EE90,  // Light green
                'movementCost' => 1,
                'defense' => 1,
                'resources' => 2
            ],
            self::FOREST => [
                'name' => 'Forest',
                'color' => 0x228B22,  // Forest green
                'movementCost' => 2,
                'defense' => 3,
                'resources' => 3
            ],
            self::MOUNTAIN => [
                'name' => 'Mountain',
                'color' => 0x808080,  // Gray
                'movementCost' => 3,
                'defense' => 4,
                'resources' => 4
            ],
            self::WATER => [
                'name' => 'Water',
                'color' => 0x4169E1,  // Royal Blue
                'movementCost' => 0,
                'defense' => 0,
                'resources' => 1
            ],
            self::DESERT => [
                'name' => 'Desert',
                'color' => 0xF4A460,  // Sandy Brown
                'movementCost' => 2,
                'defense' => 1,
                'resources' => 1
            ],
            self::SWAMP => [
                'name' => 'Swamp',
                'color' => 0x556B2F,  // Dark Olive Green
                'movementCost' => 3,
                'defense' => 2,
                'resources' => 2
            ]
        };
    }
} 