<?php

namespace App\Domain\Shared\Trait;

/**
 * DomainEventsTrait - Trait for managing domain events in aggregate roots
 *
 * Provides consistent and encapsulated domain event management for entities.
 * Follows DDD pattern for aggregate roots that need to publish domain events.
 * Uses proper encapsulation with private storage and controlled access.
 */
trait DomainEventsTrait
{
    /** @var array<object> Domain events generated by this aggregate */
    private array $domainEvents = [];

    /**
     * Records a domain event for later publishing
     *
     * @param object $event Domain event to record
     * @return void
     */
    protected function recordDomainEvent(object $event): void
    {
        $this->domainEvents[] = $event;
    }

    /**
     * Gets all recorded domain events
     *
     * @return array<object> Array of domain events
     */
    public function getDomainEvents(): array
    {
        return $this->domainEvents;
    }

    /**
     * Clears all recorded domain events
     * 
     * Should be called after events have been published to external systems.
     *
     * @return void
     */
    public function clearDomainEvents(): void
    {
        $this->domainEvents = [];
    }

    /**
     * Checks if there are any recorded domain events
     *
     * @return bool True if events are pending
     */
    public function hasDomainEvents(): bool
    {
        return !empty($this->domainEvents);
    }

    /**
     * Gets the count of recorded domain events
     *
     * @return int Number of pending events
     */
    public function getDomainEventsCount(): int
    {
        return count($this->domainEvents);
    }

    /**
     * Records multiple domain events at once
     *
     * @param array<object> $events Array of domain events to record
     * @return void
     */
    protected function recordDomainEvents(array $events): void
    {
        foreach ($events as $event) {
            $this->recordDomainEvent($event);
        }
    }

    /**
     * Gets and clears all domain events in one operation
     * 
     * Useful for event publishing scenarios where you need atomic
     * retrieval and clearing of events.
     *
     * @return array<object> Array of domain events (now cleared)
     */
    public function pullDomainEvents(): array
    {
        $events = $this->domainEvents;
        $this->clearDomainEvents();
        return $events;
    }
} 